version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nadinsoft_network

  nadinsoft.api:
    image: ${DOCKER_REGISTRY-}nadinsoftapi
    build:
      context: .
      dockerfile: NadinSoft.API/Dockerfile
    depends_on:
      - sqlserver
    environment:  # Use environment to set the connection string
      ConnectionStrings__MSSqlServer: "Server=sqlserver,1433;Database=NadineSoft;User Id=sa;Password=YourStrong!Passw0rd;MultipleActiveResultSets=true;TrustServerCertificate=true;"
    networks:
      - nadinsoft_network

networks:
  nadinsoft_network:  # Define the custom network

volumes:
  sqlserver_data:
